baseurl      = "https://davikawasaki.com/hugo-website-test/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "Jane Doe"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  footerRight='Made with &#10084; by <a href=\"https://github.com/davikawasaki\">Davi Kawasaki</a>'

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    languageName = "EN"
    title = "Hello Friend NG"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/kawasaki/"
      logoHomeLink = ""
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [languages.pt-br]
    languageName = "PT"
    title = "Olá Friend NG"
    subtitle = "Um tema simples para o Hugo"
    homeSubtitle = "Um simples e lindo blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leia outros posts"
    footerLeft='Estrutura e tema desenvolvido com <a href=\"http://gohugo.io\">Hugo</a>'
    footerRight='Desenvolvido com &#10084; por <a href=\"https://github.com/davikawasaki\">Davi Kawasaki</a>'

    [languages.pt-br.params.logo]
      logoText = "$ cd /home/kawasaki/"
      logoHomeLink = "pt-br/"
  
  [languages.da-dk]
    languageName = "DK"
    title = "Hej ven NG"
    subtitle = "Et simpelt tema for Hugo"
    homeSubtitle = "Et simpelt og smuk blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Læs andre indlæg"
    footerLeft='Drevet af <a href=\"http://gohugo.io\">Hugo</a>'
    footerRight='Udviklet med &#10084; af <a href=\"https://github.com/davikawasaki\">Davi Kawasaki</a>'

    [languages.da-dk.params.logo]
      logoText = "$ cd /home/kawasaki/"
      logoHomeLink = "da-dk/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "blog/"